<h1>
<?php 
echo $this->title;
?>
</h1>



<div class="form-signin">
	<h2 class="form-signin-heading">Please sign in</h2>
	<?php echo $this->form;?>
	<?php /*?>
	<form >
	        <input type="text" class="form-control" placeholder="Email address" required="" autofocus="">
	        <input type="password" class="form-control" placeholder="Password" required="">
	        <label class="checkbox">
	          <input type="checkbox" value="remember-me"> Remember me
	        </label>
	        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
	*/?>
</div>

