<form class="form-signin" method="POST">
        <h2 class="form-signin-heading">Registrarse</h2>
         <input type="text" name="display_name" class="form-control" placeholder="Username" autofocus required>
         <input type="text" name="name" class="form-control" placeholder="Name" required>
        <input type="text" name="email" class="form-control" placeholder="Email address" required>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <input type="password" class="form-control" placeholder="Confirm password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Registrarse</button>
      </form>