<div id="lang_search"></div>
<form class="navbar-form navbar-left" role="locale" id="locale" method="post" action="/default/index/changelanguage">
	<select name="locale" class="form-control" onchange="document.getElementById('locale').submit();">
	  <option value="" >--</option>
	  <option value="en_En">English</option>
	  <option value="es_ES">Español</option>
	</select>
	<input type='hidden' name='refer' value='<? echo $_SERVER['REQUEST_URI'];?>' />
</form>

<form class="navbar-form navbar-left" role="search" method="post" action="/backend/index/search">
      <div class="form-group">
        <input type="text" class="form-control" name="searchtext" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>