
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">

          <div class="list-group">
            <a href="<?php echo $this->url(array('controller'=>'albums', 
 'action'=>'index'));?>" class="list-group-item active">Albums</a>
            <a href="<?php echo $this->url(array('controller'=>'user', 
 'action'=>'index'));?>" class="list-group-item">Users</a>
            <a href="<?php echo $this->url(array('controller'=>'films', 
 'action'=>'index'));?>" class="list-group-item">Films</a>
            <a href="<?php echo $this->url(array('controller'=>'festivales', 
 'action'=>'index'));?>" class="list-group-item">Festivals</a>
            <a href="<?php echo $this->url(array('controller'=>'comments', 
 'action'=>'index'));?>" class="list-group-item">Comments</a>
          </div>

        </div><!--/span-->

