
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">

          <div class="list-group">
            <a href="<?php echo $this->url(
            		array('module'=>'developers', 
						  'controller'=>'albums',
						  'action'=>'index'));?>" 
					class="list-group-item active">Albums</a>
            <a href="<?php echo $this->url(array('module'=>'user', 'controller'=>'user', 
 'action'=>'index'));?>" class="list-group-item">Users</a>
            <a href="<?php echo $this->url(array('module'=>'films', 'controller'=>'index', 
 'action'=>'index'));?>" class="list-group-item">Films</a>
            <a href="<?php echo $this->url(array('module'=>'festivals', 'controller'=>'index', 
 'action'=>'index'));?>" class="list-group-item">Festivals</a>
            <a href="<?php echo $this->url(array('module'=>'', 'controller'=>'comments', 
 'action'=>'index'));?>" class="list-group-item">Comments</a>
          </div>

        </div><!--/span-->

