<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo $this->url(array('controller'=>'index', 
	 											'action'=>'index'));
	            	?>">Feed Films</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            
            <li><a href="<?php echo $this->url(array('module'=>'users',
            										 'controller'=>'index', 
	 												 'action'=>'index'));
	            	?>">User account</a></li>
            <li><a href="<?php echo $this->url(array('module'=>'author',
            										 'controller'=>'index', 
	 												 'action'=>'logout'));
	            	?>">Logout</a></li>
          
          <?php if(Zend_Auth::getInstance()->hasIdentity()):?>
          <li>
        	<a href="#" title="Edit your profile">Hello, <?=Zend_Auth::getInstance()->getIdentity()->display_name;?></a>
          </li>
          <?php endif;?>
          </ul>
          
			<?php echo $this->partial('partials/backend/lang_search.phtml');?>          
          
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->