<div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Feed Films</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'about'));?>">About</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contact'));?>">Contact</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuario <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url(array('controller' => 'author', 'action' => 'login'));?>">Login</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'author', 'action' => 'register'));?>">Registrarse</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'author', 'action' => 'logout'));?>">Salir</a></li>
                  </ul>
                </li>
                <li><a href="<?php echo $this->url(array('controller' => 'backend', 'action' => 'index'));?>">Backend</a></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
    
    
    
    
    
    
    
    
    