<?php 
$this->title = "My Festivals";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'festivales', 
'action'=>'add'));?>">Add new album</a></p>
<table>
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach($this->festivales as $festival) : ?>
	<tr>
		<td><?php echo $this->escape($festival->name);?></td>
		<td><?php echo $this->escape($festival->description);?></td>
		<td><?php echo $this->escape($festival->date);?></td>
		<td><?php echo $this->escape($festival->create);?></td>
		<td><?php echo $this->escape($festival->update);?></td>

		<td>
			<a href="<?php echo $this->url(array('controller'=>'festivales',
			'action'=>'edit', 'id'=>$festival->idfestival));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'festivales',
'action'=>'delete', 'id'=>$festival->idfestival));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>
