<?php 
$this->title = "My Films";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('module' => 'films', 'controller'=>'index', 'action'=>'add'), null, true);?>">Add new film</a></p>
<table>
<tr>
 <th>IdUser</th>
 <th>Title</th>
 <th>Director</th>
 <th>&nbsp;</th>
</tr>
<?php foreach($this->paginator as $film) : ?>
<tr>
 <td><?php echo $this->escape($film->iduser);?></td>
 <td><?php echo $this->escape($film->title);?></td>
 <td><?php echo $this->escape($film->director);?></td>
<td>
<a href="<?php echo $this->url(array('module' => 'films', 'controller'=>'index',
'action'=>'edit', 'id'=>$film->idfilm), null, true);?>">Edit</a>
<a href="<?php echo $this->url(array('module' => 'films', 'controller'=>'index',
'action'=>'delete', 'id'=>$film->idfilm), null, true);?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
<tr>
	<td colspan="4">
		<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'index/my_pagination_control.phtml'); ?>
	</td>
</tr>
</table>



