<?php foreach ($this->cols as $col) : ?>
    <ul>
    <?php foreach($col as $twits): ?>
        <?php foreach($twits as $key => $twit): ?>

            <?php if(is_numeric($key)) : ?>
                <li>
                <?php print $twit->text ?>
                </li>
            <?php else: ?>
                <?php break; ?>
            <?php endif ?>

        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endforeach ?>
