<?php foreach ($this->cols as $col) { ?>
    <?php foreach($col as $twits): ?>
        <?php foreach($twits as $key => $twit): ?>

            <?php if(is_numeric($key)) : ?>
                <pre>
                <?php print $twit->text ?>
                </pre>
            <?php else: ?>
                <?php break; ?>
            <?php endif ?>

        <?php endforeach ?>
    <?php endforeach ?>
<?php } ?>
