<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/favicon.png">
    <title>AnguilaPerro Project</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/offcanvas.css" rel="stylesheet">

  </head>

  <body>
  <?php include ("/partials/backend/navbar.phtml");?>
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
         
                <?php include ("/partials/backend/jumbotron.phtml"); ?>          
                
          <div class="row">
          	<?php 
          	echo $this->layout()->content;
          	//include ("/partials/content.phtml");
          	?>            
          </div><!--/row-->
        </div><!--/span-->
		<?php include("/partials/backend/menu.phtml");?>
        
      </div><!--/row-->
      <hr>
		<?php include ("/partials/backend/footer.phtml");?>
    </div><!--/.container-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/offcanvas.js"></script>
  </body>
</html>
