<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8" />
  <title>Feedfilms</title>
	<?php 
	    echo $this->inlineScript()->appendFile('https://code.jquery.com/jquery-1.10.2.min.js')
	                              ->appendFile('/js/bootstrap.min.js')
	                              ->appendFile('http://code.jquery.com/ui/1.10.3/jquery-ui.js')
	?>
    <?php 
        echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css')
                              ->appendStylesheet('/css/offcanvas.css')
                              ->appendStylesheet('http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css')
    ?>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>        
</head>
<body>


<?php echo $this->partial('partials/backend/nav.phtml');?>
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-right">
      	<div class="col-xs-12 col-sm-9">
	        <?php //echo $this->partial('partials/backend/content.phtml');?>
	        <?php echo $this->layout()->content ?>
        </div><!--/span-->
        <?php echo $this->partial('partials/backend/menu.phtml');?>        
      </div><!--/row-->
      <hr>
      <?php echo $this->partial('partials/backend/footer.phtml');?>
      
    </div><!--/.container-->
</body>
</html>
