<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8" />
  <title>Feedfilms</title>
    <?php 
        echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css')
                              ->appendStylesheet('/css/offcanvas.css')
    ?>
</head>
<body>

  <body>
  <?php include ("/partials/backend/navbar.phtml");?>
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
         
                <?php include ("/partials/backend/jumbotron.phtml"); ?>          
                
          <div class="row">
          	<?php 
          	echo $this->layout()->content;
          	//include ("/partials/content.phtml");
          	?>            
          </div><!--/row-->
        </div><!--/span-->
		<?php include("/partials/backend/menu.phtml");?>
        
      </div><!--/row-->
      <hr>
		<?php include ("/partials/backend/footer.phtml");?>
    </div><!--/.container-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/offcanvas.js"></script>
  </body>
</html>
