<?php
$this->title = "Delete comment";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->comment["body"]); ?>' by
'<?php echo $this->escape($this->comment["iduser"]); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="idcomment" value="<?php echo $this->comment["idcomment"]; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>