<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8" />
  <title>Feedfilms</title>
    <?php 
        echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css')
                              ->appendStylesheet('/css/signin.css')
    ?>
</head>
<body>

<div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="form-control" placeholder="Email address" required="" autofocus="">
        <input type="password" class="form-control" placeholder="Password" required="">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->
<?php echo $this->layout()->content ?>

<?php 
    echo $this->inlineScript()->appendFile('https://code.jquery.com/jquery-1.10.2.min.js')
                              ->appendFile('/js/bootstrap.min.js')
?>
</body>
</html>
